--- #YAML:1.0
name:                Term-Emit-Format-HTML
version:             0.0.2
abstract:            Formats Term::Emit output into HTML
license:             ~
author:              
    - Steve Roscio <roscio@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
